-- ============================================
-- ShareSpace Supabase Setup
-- ============================================

create table if not exists public.sharespace_shares (
    id bigint generated by default as identity primary key,
    share_id text not null unique,
    photo_path text,
    latitude double precision,
    longitude double precision,
    accuracy double precision,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ============================================
-- RLS
-- ============================================

alter table public.sharespace_shares
enable row level security;


-- ============================================
-- STORAGE BUCKET
-- ============================================

insert into storage.buckets (
    id,
    name,
    public
)

values (
    'sharespace',
    'sharespace',
    false
)

on conflict (id)
do update
set public = false;


-- ============================================
-- STORAGE POLICIES
-- ============================================

drop policy if exists
"ShareSpace service select"
on storage.objects;


drop policy if exists
"ShareSpace service insert"
on storage.objects;


drop policy if exists
"ShareSpace service update"
on storage.objects;


drop policy if exists
"ShareSpace service delete"
on storage.objects;


create policy
"ShareSpace service select"

on storage.objects

for select

to service_role

using (
    bucket_id = 'sharespace'
);


create policy
"ShareSpace service insert"

on storage.objects

for insert

to service_role

with check (
    bucket_id = 'sharespace'
);


create policy
"ShareSpace service update"

on storage.objects

for update

to service_role

using (
    bucket_id = 'sharespace'
)

with check (
    bucket_id = 'sharespace'
);


create policy
"ShareSpace service delete"

on storage.objects

for delete

to service_role

using (
    bucket_id = 'sharespace'
);


-- ============================================
-- VERIFY
-- ============================================

select *
from public.sharespace_shares
order by updated_at desc
limit 20;
