create table if not exists public.sharespace_shares (
    id bigint generated by default as identity primary key,
    photo_path text not null,
    latitude double precision,
    longitude double precision,
    accuracy double precision,
    created_at timestamptz not null
        default timezone('utc', now())
);

alter table public.sharespace_shares enable row level security;

-- The Python server uses the Supabase service_role key,
-- so server-side requests bypass these policies.

create index if not exists sharespace_shares_created_idx
on public.sharespace_shares (created_at desc);
