-- ============================================
-- ShareSpace - Supabase Database Setup
-- ============================================

-- 1. Main shares table
create table if not exists public.sharespace_shares (
    id bigint generated by default as identity primary key,
    share_id text not null,
    photo_path text,
    latitude double precision,
    longitude double precision,
    accuracy double precision,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- 2. Make sure all required columns exist
alter table public.sharespace_shares
    add column if not exists share_id text;

alter table public.sharespace_shares
    add column if not exists photo_path text;

alter table public.sharespace_shares
    add column if not exists latitude double precision;

alter table public.sharespace_shares
    add column if not exists longitude double precision;

alter table public.sharespace_shares
    add column if not exists accuracy double precision;

alter table public.sharespace_shares
    add column if not exists active boolean default true;

alter table public.sharespace_shares
    add column if not exists created_at timestamptz default now();

alter table public.sharespace_shares
    add column if not exists updated_at timestamptz default now();


-- 3. Indexes
create index if not exists sharespace_shares_created_at_idx
on public.sharespace_shares (created_at desc);

create unique index if not exists sharespace_shares_share_id_uidx
on public.sharespace_shares (share_id);


-- 4. Enable Row Level Security
alter table public.sharespace_shares enable row level security;


-- ============================================
-- STORAGE
-- ============================================

-- Create the photo bucket if it doesn't already exist.
-- Private bucket: photos are accessed by the server using
-- the Supabase service/secret key and signed URLs.
insert into storage.buckets
    (id, name, public, file_size_limit)
values
    ('sharespace', 'sharespace', false, 10485760)
on conflict (id) do update
set
    public = false,
    file_size_limit = 10485760;


-- ============================================
-- STORAGE POLICIES
-- ============================================

-- Remove old policies if they exist
drop policy if exists "ShareSpace service upload" on storage.objects;
drop policy if exists "ShareSpace service read" on storage.objects;
drop policy if exists "ShareSpace service delete" on storage.objects;


-- Server/service-role access is used by Render.
-- The browser never receives the secret/service key.

create policy "ShareSpace service upload"
on storage.objects
for insert
to service_role
with check (
    bucket_id = 'sharespace'
);


create policy "ShareSpace service read"
on storage.objects
for select
to service_role
using (
    bucket_id = 'sharespace'
);


create policy "ShareSpace service delete"
on storage.objects
for delete
to service_role
using (
    bucket_id = 'sharespace'
);


-- ============================================
-- DONE
-- ============================================
